[package]
name = "bayesplay"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "^0.12.1"
rmath = {version = "0.1.0", path = "../rmath"}
serde = {version = "1.0.197", features = ["derive"]}
thiserror = "1.0.58"
anyhow = "1.0.81"
approx = "0.5.1"
enum_dispatch = "0.3"

